export const BookingTypes = {
    START_FETCH_ALL_BOOKING: 'START_FETCH_ALL_BOOKING',
    SUCCESS_FETCH_ALL_BOOKING: 'SUCCESS_FETCH_ALL_BOOKING',
    START_FETCH_ALL_WORKORDER: 'START_FETCH_ALL_WORKORDER',
    SUCCESS_FETCH_ALL_WORKORDER: 'SUCCESS_FETCH_ALL_WORKORDER'
};