export const loadDataInputTypes = {
    START_FETCH_TYPE_CONTRACT: 'START_FETCH_TYPE_CONTRACT',
    SUCCESS_FETCH_TYPE_CONTRACT: 'SUCCESS_FETCH_TYPE_CONTRACT',
    FAILED_FETCH_TYPE_CONTRACT: 'FAILED_FETCH_TYPE_CONTRACT',
    START_FETCH_RECOMMENDED_JOBS: 'START_FETCH_RECOMMENDED_JOBS',
    SUCCESS_FETCH_RECOMMENDED_JOBS: 'SUCCESS_FETCH_RECOMMENDED_JOBS',
    START_FETCH_PROVINCE: 'START_FETCH_PROVINCE',
    SUCCESS_FETCH_PROVINCE: 'SUCCESS_FETCH_PROVINCE',
    FAILED_FETCH_PROVINCE: 'FAILED_FETCH_PROVINCE'
}