export const JobListTypes = {
	START_FETCH_JOB_LIST: 'START_FETCH_JOB_LIST',
	SUCCESS_FETCH_JOB_LIST: 'SUCCESS_FETCH_JOB_LIST',
	FAILED_FETCH_JOB_LIST: 'FAILED_FETCH_JOB_LIST',
	START_FETCH_JOB_DETAIL: 'START_FETCH_JOB_DETAIL',
	SUCCESS_FETCH_JOB_DETAIL: 'SUCCESS_FETCH_JOB_DETAIL',
	START_FETCH_REVIEW: 'START_FETCH_REVIEW',
	SUCCESS_FETCH_REVIEW: 'SUCCESS_FETCH_REVIEW',
	START_INSERT_BOOKING: 'START_INSERT_BOOKING',
	SUCCESS_INSERT_BOOKING: 'SUCCESS_INSERT_BOOKING',
	SAVE_JOB_BOOKING:'SAVE_JOB_BOOKING',
	START_SEARCH_JOB: 'START_SEARCH_JOB',
	START_INSERT_JOB: 'START_INSERT_JOB',
	SUCCESS_INSERT_JOB: 'SUCCESS_INSERT_JOB'
};