export const userTypes = {
	TOGGLE_DROPDOWN: 'TOGGLE_DROPDOWN',
	TOGGLE_REGISTER_DROPDOWN: 'TOGGLE_REGISTER_DROPDOWN',
	TOOGLE_SET_RECOMMENDED_JOB: 'TOOGLE_SET_RECOMMENDED_JOB',
	TOOGLE_SET_CONTRACT_TYPE: 'TOOGLE_SET_CONTRACT_TYPE',
	TOOGLE_SET_CITY_JOB: 'TOOGLE_SET_CITY_JOB',
	LOGIN_USER: 'LOGIN_USER',
	SUCCESS_LOGIN: 'SUCCESS_LOGIN',
	FAILED_LOGIN_USER: 'FAILED_LOGIN_USER',
	SUCCESS_DECRYPT_USER: 'SUCCESS_DECRYPT_USER',
	IS_LOGIN_OR_NOT: 'IS_LOGIN_OR_NOT',
	USER_LOGGED_OUT: 'USER_LOGGED_OUT',
	START_REGISTER_USER: 'START_REGISTER_USER',
	SUCCESS_REGISTER_USER: 'SUCCESS_REGISTER_USER'
};
